### ISSUE TITLE
Failing to install rasterSP package

### ISSUE THREAD

**Issue by Ratheesh-kv** [RS-eco/climateNiche#1]
Hi,

I was trying to install the rasterSP package for my work but unfortunately I fail to install and I am getting the error. So, could you please help me to solve this issue

Thanks
Ratheesh

Please see the error message. I have already installed remote package.

if(!"rasterSp" %in% installed.packages()[,"Package"]) remotes::install_github("RS-eco/rasterSp", build_vignettes = T)
Downloading GitHub repo RS-eco/rasterSp@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                              
2: CRAN packages only               
3: None                             
4: rlang    (0.4.8  -> 0.4.9) [CRAN]
5: magrittr (1.5    -> 2.0.1) [CRAN]
6: vctrs    (0.3.4  -> 0.3.5) [CRAN]
7: pillar   (1.4.6  -> 1.4.7) [CRAN]
8: cli      (2.1.0  -> 2.2.0) [CRAN]
9: raster   (3.3-13 -> 3.4-5) [CRAN]

Enter one or more numbers, or an empty line to skip updates:3
√  checking for file 'C:\Users\Ratheeshkv\AppData\Local\Temp\RtmpOMUZQg\remotes429c7c48250d\RS-eco-rasterSp-206611c/DESCRIPTION' (1.4s)
-  preparing 'rasterSp': (1.2s)
√  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes (609ms)
E  creating vignettes (9m 55.6s)
   --- re-building 'iucn-invasions.Rmd' using rmarkdown
   Quitting from lines 22-28 (iucn-invasions.Rmd) 
   Error: processing vignette 'iucn-invasions.Rmd' failed with diagnostics:
   length(dsn) == 1L is not TRUE
   --- failed re-building 'iucn-invasions.Rmd'
   
   SUMMARY: processing the following file failed:
     'iucn-invasions.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'rasterSp' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Quitting from lines 22-28 (iucn-invasions.Rmd) 
E> Error: processing vignette 'iucn-invasions.Rmd' failed with diagnostics:
E> length(dsn) == 1L is not TRUE
E> --- failed re-building 'iucn-invasions.Rmd'
E> 
E> SUMMARY: processing the following file failed:
E>   'iucn-invasions.Rmd'
E> 
E> Error: Vignette re-building failed.
E> Execution halted

My R version 
version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.3                         
year           2020                        
month          10                          
day            10                          
svn rev        79318                       
language       R                           
version.string R version 4.0.3 (2020-10-10)
nickname       Bunny-Wunnies Freak Out

**Comment by RS-eco** [comment]
Dear @Ratheesh-kv, sorry I only saw this issue now. But I believe this has been fixed now. Otherwise, running
install_github with build_vignettes=F will do solve your error:
`remotes::install_github("RS-eco/rasterSp", build_vignettes = T)`

**Comment by Ratheesh-kv** [comment]
Hi,

Thanks very much for your reply.

Sincerely
Ratheesh
