### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by zenrabbit** [RS-eco/climateNiche#2]
I love this package and the idea. Thank you.
I have 4 plant species from gbif, got worldclim, and worked though first two chunks of work, but am stuck on climateNiche specific functions.

a. see observations_joined, thank you again for laying out all steps.
b. now, what, I want to do three of the functions you provide in a new rmd, I read in as df, do I need to reset as spatial class etc?

```{r}
library(tidyverse)
library(climateNiche)
library(raster)

#sample species
sp_data <- read_csv("data/observations_joined.csv")

#think need to change class of sp_data 
#data	raster layer or stack of the presence of one or multiple species, also takes a list

#use raster coordinates and crs functions?

#then climateNiche has three functions

#two key things
#1. plot species ranges/niches
#2. plot climate envelope

#use only temp?
#displayNiche for one species at a time or can create list to do >1
#plotSp to compare species on map
#climateEnvelope for one species at a time


[observations_joined.csv](https://github.com/RS-eco/climateNiche/files/10714516/observations_joined.csv)

**Comment by zenrabbit** [comment]
and the climateEnvelope function looks awesome, if I do a plot for each of the 4 species, two quick Qs

a. does red and black polygons you show in plotted example represent different data sources or different estimated niches?
b. is there an underlying geom_stat style function or statistic to report to contrast which species likes it 'hottest' or has biggest niche?

sorry if this is all really obvious, new to me, and seems really cool.
thanks!

**Comment by RS-eco** [comment]
Hey,

here a first try on this:

```{r}
library(tidyverse)
library(climateNiche)
library(raster)

#sample species
sp_data <- read_csv("data/observations_joined.csv")
colnames(sp_data)
colnames(sp_data)[1:3] <- c("scientificName", "Lat", "Long")
unique(sp_data$scientificName)

dat_brom <- sp_data %>% filter(scientificName == "Bromus rubens")
dat_lay <- sp_data %>% filter(scientificName == "Layia platyglossa")
dat_pha <- sp_data %>% filter(scientificName == "Phacelia tanacetifolia")
dat_sal <- sp_data %>% filter(scientificName == "Salvia columbariae")

sp_dat_list <- split(sp_data, f=sp_data$scientificName, drop=F)

#1. plot species ranges/niches

plotSp(data=dat_brom, extent=c(-160, -100, 30, 40), country=T)
plotSp(data=sp_dat_list, extent=c(-160, -100, 30, 40), country=T)

# Plot locations
library(ggmap2) # For getting outline
ggplot() + geom_point(data=dat_brom, aes(x=Long, y=Lat), col="red") + 
  geom_point(data=dat_lay, aes(x=Long, y=Lat), col="blue") + 
  geom_point(data=dat_pha, aes(x=Long, y=Lat), col="green") + 
  geom_point(data=dat_sal, aes(x=Long, y=Lat), col="yellow") + 
  geom_sf(data=outline, fill="transparent", color="black") + 
  coord_sf(xlim=c(-122,-115), ylim=c(34,38), expand=F) + theme_bw()

# Plot niche
displayNiche(data=dat_brom, res=10, var=c("tmin", "tmax", "prec"), path=getwd())

displayNiche(data=sp_dat_list, path=getwd(), var=c("bio5", "bio12", "bio15"), res=10)

#2. plot climate envelope
climateEnvelope(data=sp_dat_list[c(1:2)], path=getwd())
```

The sp_plot function does not seem to work properly with your data, so I simply created the plot directly with ggplot2.
displayNiche works fine with the list of species, but downloads the Worldclim data internally, I will have to add an additional argument, if you have already provided the worldclim data in the data.frame yourself.
The climateEnvelope function currently only works with two species, in the README example red and black refer to two different data sets. I will modify this accordingly, but I will be away the whole of next week, so won't manage to deal with any of this before the 20th of February.

**Comment by zenrabbit** [comment]
Incredible, trying it now.
also reading up on all this cool stuff in the literature!
Thank you for the inspiration and the help too!!
wow!!

**Comment by zenrabbit** [comment]
ok got my head around it.
a. display niche is like geom_boxplots for key vars
b. climate envelope uses adehabitatHR::mcp then plots out the estimate mcps' ie home ranges for each species.

correct?
COOL stuff and good process.

**Comment by RS-eco** [comment]
Yes, this is true. Do you still need any help or modifications of the functions or have you already modified the code yourself?

**Comment by RS-eco** [comment]
Finally, I managed to fix most of the issues that emerged from your request.
Here is now an updated version of using the different functions with your dataset:

``` r
library(dplyr)
library(climateNiche)

#load sample species data
sp_data <- read.csv("observations_joined.csv")

# check column names
colnames(sp_data)

# Re-specify column names so climateNiche functions work
colnames(sp_data)[1:3] <- c("scientificName", "Lat", "Long")
unique(sp_data$scientificName)
#> [1] "Bromus rubens"          "Layia platyglossa"      "Phacelia tanacetifolia"
#> [4] "Salvia columbariae"

# Split data.frame into list by species name
sp_dat_list <- split(sp_data, f=sp_data$scientificName, drop=F)

# 1. Plot species ranges/locations
plotSp(data=sp_dat_list, extent=c(-122, -115, 34, 38), world=T, cut=T, geom="point")
```

![](https://i.imgur.com/VGDRHWN.png)

``` r

# 2. Plot species niches
displayNiche(data=sp_dat_list, lon="Long", lat="Lat", path=getwd(), 
             variables=c("bio5", "bio12", "bio15"), download=F)
```

![](https://i.imgur.com/4sxCtBb.png)

``` r

# 3. Plot species climate envelope
library(patchwork)
(climateEnvelope(data=sp_dat_list[[1]], path=getwd()) + 
    climateEnvelope(data=sp_dat_list[[2]], path=getwd())) / 
  (climateEnvelope(data=sp_dat_list[[3]], path=getwd()) + 
     climateEnvelope(data=sp_dat_list[[4]], path=getwd())) + plot_layout(guides="collect")
```

![](https://i.imgur.com/xACdne6.png)

<sup>Created on 2023-02-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Regarding your questions on the climateEnvelope() function.

- Does red and black polygons you show in plotted example represent different data sources or different estimated niches?
Red and black points/polygons show different time periods. I have now added a legend showing this to the plot!

- Is there an underlying geom_stat style function or statistic to report to contrast which species likes it 'hottest' or has biggest niche?

No, but I am sure you can infer these from your dataset yourself, i.e. regarding the hottest niche, you could simply calculate the maximum or mean temperature of the maximum temperature.

I hope this resolves any open issues. Could you maybe send me the code for recreating the dataset you have sent me, than I would include this as a vignette to the package. Cheers!
